/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'primary':                      '#0058be',
        'on-primary':                   '#ffffff',
        'primary-container':            '#2170e4',
        'on-primary-container':         '#fefcff',
        'primary-fixed':                '#d8e2ff',
        'primary-fixed-dim':            '#adc6ff',
        'on-primary-fixed':             '#001a42',
        'on-primary-fixed-variant':     '#004395',
        'secondary':                    '#565e74',
        'on-secondary':                 '#ffffff',
        'secondary-container':          '#dae2fd',
        'on-secondary-container':       '#5c647a',
        'secondary-fixed':              '#dae2fd',
        'secondary-fixed-dim':          '#bec6e0',
        'on-secondary-fixed':           '#131b2e',
        'on-secondary-fixed-variant':   '#3f465c',
        'tertiary':                     '#006947',
        'on-tertiary':                  '#ffffff',
        'tertiary-container':           '#00855b',
        'on-tertiary-container':        '#f5fff6',
        'tertiary-fixed':               '#6ffbbe',
        'tertiary-fixed-dim':           '#4edea3',
        'on-tertiary-fixed':            '#002113',
        'on-tertiary-fixed-variant':    '#005236',
        'error':                        '#ba1a1a',
        'on-error':                     '#ffffff',
        'error-container':              '#ffdad6',
        'on-error-container':           '#93000a',
        'background':                   '#f8f9ff',
        'on-background':                '#0b1c30',
        'surface':                      '#f8f9ff',
        'on-surface':                   '#0b1c30',
        'surface-variant':              '#d3e4fe',
        'on-surface-variant':           '#424754',
        'surface-container-lowest':     '#ffffff',
        'surface-container-low':        '#eff4ff',
        'surface-container':            '#e5eeff',
        'surface-container-high':       '#dce9ff',
        'surface-container-highest':    '#d3e4fe',
        'surface-bright':               '#f8f9ff',
        'surface-dim':                  '#cbdbf5',
        'surface-tint':                 '#005ac2',
        'outline':                      '#727785',
        'outline-variant':              '#c2c6d6',
        'inverse-surface':              '#213145',
        'inverse-on-surface':           '#eaf1ff',
        'inverse-primary':              '#adc6ff',
      },
      spacing: {
        'xs':             '4px',
        'unit':           '4px',
        'sm':             '8px',
        'md':             '16px',
        'lg':             '24px',
        'xl':             '32px',
        'margin-mobile':  '16px',
        'margin-desktop': '48px',
        'gutter':         '20px',
      },
      fontSize: {
        'h1':          ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2':          ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3':          ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg':     ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md':    ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'num-display': ['32px', { lineHeight: '40px', letterSpacing: '-0.03em', fontWeight: '700' }],
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
